
name: Draft Release

on:
  push:
    tags:

jobs:
  build:
    uses: Jibby-Games/Flappy-Race/.github/workflows/build.yml@main
  draft_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v2
        with:
          name: FlappyRace-windows-${{ github.sha }}
          path: builds/FlappyRace-${{ github.ref_name }}-Windows
      - name: Download Mac Build
        uses: actions/download-artifact@v2
        with:
          name: FlappyRace-mac-${{ github.sha }}
          path: builds/FlappyRace-${{ github.ref_name }}-Mac
      - name: Download Linux Build
        uses: actions/download-artifact@v2
        with:
          name: FlappyRace-linux-${{ github.sha }}
          path: builds/FlappyRace-${{ github.ref_name }}-Linux
      - name: Prepare Windows
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: FlappyRace-${{ github.ref_name }}-Windows.zip
          path: FlappyRace-${{ github.ref_name }}-Windows/*
          directory: builds/
      - name: Prepare Mac
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: FlappyRace-${{ github.ref_name }}-Mac.zip
          path: FlappyRace-${{ github.ref_name }}-Mac/*
          directory: builds/
      - name: Prepare Linux
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: FlappyRace-${{ github.ref_name }}-Linux.zip
          path: FlappyRace-${{ github.ref_name }}-Linux/*
          directory: builds/
      - name: Checkout
        uses: actions/checkout@v2
      # TODO: see if this support our changelog format again in future
      # - name: Update Changelog
      #   uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
      #   with:
      #     tag: ${{ github.ref_name }}
      - name: Extract Release Notes
        uses: ffurrer2/extract-release-notes@v1
        id: extract-release-notes
      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Flappy Race ${{ github.ref_name }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: true
          files: |
            builds/FlappyRace-*-*.zip