
name: Draft Release

on:
  push:
    # branches:
    #   - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: Jibby-Games/Flappy-Race/.github/workflows/build.yml@main
  draft_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Testing reuse
        run: |
          ls -al
          ls -al builds/windows