
name: Draft Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: The tag to release
        type: string

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update project and export versions
        run: |
          sed -i "s/config\/version=.*/config\/version=\"v${{ github.event.inputs.tag }}\"/g" project.godot
          sed -i "s/=\"[0-9]\.[0-9]\.[0-9]\"/\"${{ github.event.inputs.tag }}\"/g" export_presets.cfg
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ github.event.inputs.tag }}
  build:
    uses: Jibby-Games/Flappy-Race/.github/workflows/build.yml@main
    needs: update_version
  draft_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Windows Build
        uses: actions/download-artifact@v2
        with:
          name: FlappyRace-windows-${{ github.sha }}
          path: builds/FlappyRace-${{ github.event.inputs.tag }}-Windows
      - name: Download Mac Build
        uses: actions/download-artifact@v2
        with:
          name: FlappyRace-mac-${{ github.sha }}
          path: builds/FlappyRace-${{ github.event.inputs.tag }}-Mac
      - name: Download Linux Build
        uses: actions/download-artifact@v2
        with:
          name: FlappyRace-linux-${{ github.sha }}
          path: builds/FlappyRace-${{ github.event.inputs.tag }}-Linux
      - name: Prepare Windows
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: FlappyRace-${{ github.event.inputs.tag }}-Windows.zip
          path: FlappyRace-${{ github.event.inputs.tag }}-Windows/*
          directory: builds/
      - name: Prepare Mac
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: FlappyRace-${{ github.event.inputs.tag }}-Mac.zip
          path: FlappyRace-${{ github.event.inputs.tag }}-Mac/*
          directory: builds/
      - name: Prepare Linux
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: FlappyRace-${{ github.event.inputs.tag }}-Linux.zip
          path: FlappyRace-${{ github.event.inputs.tag }}-Linux/*
          directory: builds/
      - name: Extract Release Notes
        uses: ffurrer2/extract-release-notes@v1
        id: extract-release-notes
      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.events.inputs.tag }}
          name: Flappy Race ${{ github.event.inputs.tag }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: true
          files: |
            builds/FlappyRace-*-*.zip